DESC customer;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount_usd) AS total_revenue
FROM customer 
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount_usd FROM customer 
WHERE discount_applied='Yes'
AND purchase_amount_usd > (
    SELECT AVG(purchase_amount_usd)
    FROM customer);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,
ROUND(AVG(review_rating), 2) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type,
ROUND(AVG(purchase_amount_usd), 2) AS avg_spend
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
SELECT IF(subscription_status='Yes', 'Subscribers', 'Non-subscribers') AS customer,
COUNT(*) AS total_customers,
ROUND(AVG(purchase_amount_usd), 2) AS avg_spend,
SUM(purchase_amount_usd) AS total_revenue 
FROM customer
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND(SUM(IF(discount_applied='Yes', 1, 0))/COUNT(*)*100, 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases=1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
END AS customer_segment
FROM customer)
SELECT customer_segment, COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
WITH ranked_products AS (
SELECT category,
item_purchased,
COUNT(*) AS count,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(*)) AS ranking
FROM customer
GROUP BY category,
item_purchased )
SELECT category,
item_purchased,
count, 
ranking 
FROM ranked_products
WHERE ranking <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases)
-- also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer 
WHERE previous_purchases>5
GROUP BY subscription_status;

SELECT ROUND(
SUM(IF(subscription_status='Yes', 1, 0))/
(SELECT COUNT(*) FROM customer)*100,
2) AS repeat_byers_churn_rate 
FROM customer
WHERE previous_purchases>5;


-- Q10. What is the revenue contribution of each age group? 
SELECT DISTINCT age_group,
ROUND(
      SUM(purchase_amount_usd) OVER(PARTITION BY age_group)/
      SUM(purchase_amount_usd) OVER()*100, 2) AS age_group_contribution
FROM customer
ORDER BY age_group_contribution DESC;
